import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // Autogenerate sidebar from the docs folder structure
  docs: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
