name: Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release_please:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.rp.outputs.releases_created }}
      tag_name: ${{ steps.rp.outputs.tag_name }}
    steps:
      - uses: actions/checkout@v4
      - id: rp
        uses: googleapis/release-please-action@v4
        with:
          target-branch: main
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

  publish:
    name: publish to crates.io
    needs: release_please
    if: needs.release_please.outputs.releases_created == 'true'
    runs-on: ubuntu-latest
    environment: crates-io
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Configure crates.io token
        run: |
          mkdir -p $HOME/.cargo
          cat > $HOME/.cargo/credentials <<'EOF'
          [registry]
          token = "${{ secrets.CARGO_REGISTRY_TOKEN }}"
          EOF
          chmod 0600 $HOME/.cargo/credentials
      - name: Dry run
        run: cargo publish -p ferriclink-core --dry-run --allow-dirty
      - name: Publish
        run: cargo publish -p ferriclink-core --no-verify
